esphome:
  name: bluetooth-proxy-gast
  friendly_name: Bluetooth-Proxy-Gast

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dS7MmTKSvwmlnf/c/K9lTSd0pURJzWFOZBwgZHG26i0="

ota:
  - platform: esphome
    password: "b23d8b6c28553e5c47a76673c2e8a65a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Proxy-Gast"
    password: "k564NoTrlgN3"

captive_portal:
    