substitutions:
  name: esp32-bluetooth-proxy-5e4958
  friendly_name: Bluetooth Proxy 5e4958
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 8uCB1tcm3Y/ipfgCjAAj3KE+b8mPqjnFlnTBIFHjw2s=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
