esphome:
  name: neu
  friendly_name: Neu

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MAxOiqw2wEtw0bxy768my86Xz9KZ89ohC8qGfrARNEY="

ota:
  - platform: esphome
    password: "03b64d6c7a87aeaac00140dc385c8307"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Neu Fallback Hotspot"
    password: "W00LLfhjxZfe"

captive_portal:
    