homeassistant:
  enabled: true
advanced:
  network_key: '!secret.yaml network_key'
  pan_id: 40619
  ext_pan_id:
    - 114
    - 57
    - 152
    - 198
    - 248
    - 78
    - 222
    - 24
  log_level: error
  last_seen: ISO_8601_local
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: Soofou7enohNgaitah1av6ana6li9nohgoP5bohPodeip8rohxieRaiciuCahNah
frontend:
  enabled: true
  port: 8099
serial:
  port: tcp://192.168.178.104:6638
  baudrate: 115200
  adapter: zstack
device_options:
  disable_led: true
  transmit_power: 20
  homeassistant:
    last_seen:
      enabled_by_default: true
devices:
  '0x14b457fffecbadde':
    friendly_name: Ikea Fernbedienung
  '0x086bd7fffe404a82':
    friendly_name: Ikea Licht Spuele
  '0x086bd7fffe235b06':
    friendly_name: Ikea Licht Herd
  '0xa4c138442a735c69':
    friendly_name: Steckdose Wohnzimmer
    description: Roborock
  '0xa4c13838e02b32cf':
    friendly_name: Steckdose Kontrollraum
  '0xa4c138e0c3eb3318':
    friendly_name: Steckdose 3
    description: 3 Punkte
  '0xa4c13812cab3c4fc':
    friendly_name: Steckdose 4
    description: 4 Punkte
  '0x00158d008b61ad80':
    friendly_name: Balkon_Wetter
    description: |
      Temperatur, Luftfeuchte, Luftdruck vom Balkon
    pressure_calibration: 4
    pressure_precision: 0
    humidity_precision: 0
    humidity_calibration: 2.5
    temperature_precision: 1
    temperature_calibration: -2
  '0xa4c1384490e4e5ea':
    friendly_name: Gästebad_Aussentemperatur
    temperature_precision: 1
    humidity_calibration: 10
    humidity_precision: 0
    temperature_calibration: 24
  '0x54ef4410010fcba1':
    friendly_name: Lichtsensor-Schlafzimmer
  '0xa4c13862ada89947':
    friendly_name: Steckdose Computer
    description: Markierung 1
  '0xa4c1389840f71629':
    friendly_name: Steckdose Drucker/Scanner
    description: Markierung 2
  '0xa4c13825f1f83cf1':
    friendly_name: Steckdose Fernseher
    description: Markierung 3
version: 4
availability: {}
